Multiple changes
p-Roxy/Puppet pull request #1
Opened 2017-02-27 00:50 UTC by tgray-projects

Multiple changes done for UI, code clarity, functionality.

2017-02-27 07:10 UTC, tgray-projects commented
Multiple style and functionality changes to make it work.  Please let me know if you find any issues with these changes.

2017-03-01 03:01 UTC, p-Roxy requested changes
Everything looks good except the orient="vertical" selector in the range htmls need to be removed and the following needs to be added to the slider.css input="range" section:

    transform: rotate(270deg);
    -webkit-transform: rotate(270deg);
    -ms-transform: rotate(270deg);
    -o-transform: rotate(270deg);
    -moz-transform: rotate(270deg);
Thanks!

2017-03-01 23:39 UTC, tgray-projects commented
Merged in your latest changes.

2017-03-02 00:42 UTC, p-Roxy approved these changes

2017-03-02 00:42 UTC, merged